### ISSUE TITLE
Android - How to consume products (allow user to buy product even if they have purchased it past)

### ISSUE THREAD

**Issue by ryan-granlund** [iaphub/react-native-iaphub-ui#2]
On Android, is there a way to "consume" an IAP product? I need to allow the user to make a purchase even if they have already purchased the item in the past?  

iOS works fine when using a consumable IAP.

**Comment by iaphub** [comment]
Hi @ryan-granlund,

The product will be consumed automatically if the type is "consumable" on IAPHUB.
Just make sure the [Android API is configured](https://www.iaphub.com/docs/set-up-android/configure-google-play-api) otherwise IAPHUB won't be able to valide the receipt and consume the transaction.
If you're still having an error after configuring the Google API, it is because a previous purchase couldn't be validated (because the Google API didn't work), simply call the `restore()` method and it should fix it.

PS: You can check if the receipts are being validated properly on the Receipts page of the IAPHUB dashboard.

I'm closing this issue since it isn't related to the `react-native-iaphub-ui` plugin but feel free to contact our support (support@iaphub.com) if you're still having an issue.
